name: ketamiz
description: "Mobile Transportation Application"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+5

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.16
  pinput: ^6.0.1
  image_picker: ^1.1.2
  shared_preferences: ^2.3.4
  rxdart: ^0.28.0
  cached_network_image: ^3.4.1
  permission_handler: ^12.0.1
  firebase_messaging: ^16.0.4
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.4
  localization: ^2.1.1
  flutter_translate: any

  http: ^1.2.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  dotted_line: ^3.2.3
  lottie: ^3.3.1
  geocoding: ^4.0.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  image: ^4.5.4
  path: ^1.9.1
  open_filex: ^4.5.0
  firebase_core: ^4.11.0
  flutter_local_notifications: ^22.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logos/logo-square.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logos/logo-square.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/cars/
    - assets/banner/
    - assets/icons/
    - assets/i18n/
    - assets/fonts/
    - assets/lottie/
    - assets/logos/
    - assets/places.json
    - AssetManifest.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500